#!/bin/bash

SCRIPTS_HOME="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P )"
DOOPNET_HOME=$( cd -P "$SCRIPTS_HOME/../" && pwd -P )

ifconfig | while read name others ; do
case "$others" in 
"Link encap"*)
	echo $name
	;;
esac
done
