#!/bin/bash

SCRIPTS_HOME="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P )"
DOOPNET_HOME=$( cd -P "$SCRIPTS_HOME/../" && pwd -P )

NODE_ID=$(hostname)

echo -e "\nStopping netflow in host ${NODE_ID} ..."

killall fprobe
while [ $(ps ax | grep -c 'fprob[e]') -ge 1 ] ; do 
	sleep 1
done
sleep 1
killall nfcapd

