#!/bin/bash

usage() {
	echo -e "\nUsage: $0 <dst folder name (will be placed under /mnt/host-exchange)>\n"
	exit 1
}

[ $# != 1 ] && usage
DST_DIR=$1

#####################################

SCRIPTS_HOME="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P )"
DOOPNET_HOME=$( cd -P "$SCRIPTS_HOME/../" && pwd -P )

tmplist="/tmp/backup-everything.hosts"
>$tmplist
cat /etc/hosts | while read ip name ; do
	[ -z "$name" ] && continue
	[ "$name" = "localhost" ] && continue
	echo $name >> $tmplist
done

pdsh -R ssh -w  ^$tmplist $SCRIPTS_HOME/node-backup-everything $DST_DIR

host=$(cat $tmplist | (read h && echo $h))
echo -e "\nBacking up HDFS /mapred from host $host...\n"
pdsh -R ssh -w $host rm -rf /tmp/mapred
pdsh -R ssh -w $host $SCRIPTS_HOME/node-hdfs dfs -get /mapred /tmp
pdsh -R ssh -w $host cp -a /tmp/mapred /mnt/host-exchange/$DST_DIR
pdsh -R ssh -w $host rm -rf /tmp/mapred

rm -f $tmplist

