#!/bin/bash

SCRIPTS_HOME="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P )"
DOOPNET_HOME=$( cd -P "$SCRIPTS_HOME/../" && pwd -P )

HDUSER_PREFIX=/home/hduser
HADOOP_PREFIX=$HDUSER_PREFIX/hadoop
HADOOP_BIN=$HADOOP_PREFIX/bin
HADOOP_SBIN=$HADOOP_PREFIX/sbin
HADOOP_CONF_DIR=$HADOOP_PREFIX/etc/hadoop

$SCRIPTS_HOME/node-hdfs namenode -format

